# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime
import sys
from pymysql import *
import orderdin
import xgnews
import xgorder
import xggoods
import xgcustomer
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QTableWidgetItem, QHeaderView, QMessageBox

db = connect(
    host='localhost', port=3306, user='root', password='', database='pyconnect'
)

cur = db.cursor()

class xg(QtWidgets.QMainWindow,orderdin.Ui_Form):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        orderdin.Ui_Form.__init__(self)
        self.setupUi(self)

class xgcus(QtWidgets.QMainWindow,xgcustomer.Ui_Form):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        xgcustomer.Ui_Form.__init__(self)
        self.setupUi(self)

class xggoo(QtWidgets.QMainWindow,xggoods.Ui_Form):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        xggoods.Ui_Form.__init__(self)
        self.setupUi(self)

class xgnew(QtWidgets.QMainWindow,xgnews.Ui_Form):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        xgnews.Ui_Form.__init__(self)
        self.setupUi(self)

class xgord(QtWidgets.QMainWindow,xgorder.Ui_Form):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        xgorder.Ui_Form.__init__(self)
        self.setupUi(self)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(942, 569)
        self.xg1 = xg()
        self.xgcus1 = xgcus()
        self.xggoo1 = xggoo()
        self.xgnew1 = xgnew()
        self.xgord1 = xgord()

        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 721, 551))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(720, 130, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 90, 81, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 50, 81, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(720, 10, 81, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(720, 170, 41, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(720, 220, 41, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(760, 180, 171, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(760, 220, 171, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 721, 551))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)

        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(720, 0, 81, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(720, 40, 81, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(720, 230, 81, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(720, 270, 81, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(720, 330, 51, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(780, 330, 151, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(720, 100, 51, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(720, 130, 51, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(720, 160, 51, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(720, 190, 51, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(780, 100, 151, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(780, 130, 151, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(780, 160, 151, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(780, 190, 151, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 591, 551))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(590, 0, 81, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(590, 40, 81, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(600, 100, 51, 31))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(660, 100, 151, 21))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(600, 130, 51, 31))
        self.label_9.setObjectName("label_9")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(660, 130, 151, 21))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(600, 160, 61, 31))
        self.label_10.setObjectName("label_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(660, 160, 151, 21))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(600, 190, 61, 31))
        self.label_11.setObjectName("label_11")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(660, 190, 271, 21))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(600, 220, 61, 31))
        self.label_12.setObjectName("label_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(660, 220, 151, 21))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setGeometry(QtCore.QRect(590, 250, 81, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_12.setGeometry(QtCore.QRect(590, 290, 81, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(590, 330, 51, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(590, 360, 61, 31))
        self.label_14.setObjectName("label_14")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(660, 330, 151, 21))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(660, 360, 151, 21))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 591, 551))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_13.setGeometry(QtCore.QRect(590, 0, 111, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(590, 50, 51, 31))
        self.label_15.setObjectName("label_15")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(640, 50, 113, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_14.setGeometry(QtCore.QRect(590, 90, 111, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(590, 140, 71, 31))
        self.label_16.setObjectName("label_16")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_16.setGeometry(QtCore.QRect(660, 140, 113, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(590, 170, 71, 31))
        self.label_17.setObjectName("label_17")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_17.setGeometry(QtCore.QRect(660, 170, 113, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(590, 200, 71, 31))
        self.label_18.setObjectName("label_18")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_18.setGeometry(QtCore.QRect(660, 200, 113, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(590, 230, 71, 31))
        self.label_19.setObjectName("label_19")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_19.setGeometry(QtCore.QRect(660, 230, 113, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(590, 260, 71, 31))
        self.label_20.setObjectName("label_20")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_20.setGeometry(QtCore.QRect(660, 260, 113, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 501, 551))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_15.setGeometry(QtCore.QRect(500, 0, 111, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(500, 60, 54, 12))
        self.label_21.setObjectName("label_21")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_21.setGeometry(QtCore.QRect(560, 50, 113, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_16.setGeometry(QtCore.QRect(500, 90, 111, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 0, 501, 551))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(4)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_17.setGeometry(QtCore.QRect(500, 0, 111, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setGeometry(QtCore.QRect(510, 50, 61, 21))
        self.label_22.setObjectName("label_22")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_22.setGeometry(QtCore.QRect(580, 50, 113, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_18.setGeometry(QtCore.QRect(500, 80, 111, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_23 = QtWidgets.QLabel(self.tab_6)
        self.label_23.setGeometry(QtCore.QRect(510, 130, 61, 21))
        self.label_23.setObjectName("label_23")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_23.setGeometry(QtCore.QRect(580, 130, 113, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setGeometry(QtCore.QRect(510, 160, 61, 21))
        self.label_24.setObjectName("label_24")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_24.setGeometry(QtCore.QRect(580, 160, 113, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(510, 190, 61, 21))
        self.label_25.setObjectName("label_25")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_25.setGeometry(QtCore.QRect(580, 190, 113, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(510, 220, 61, 21))
        self.label_26.setObjectName("label_26")
        self.textEdit = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit.setGeometry(QtCore.QRect(580, 220, 351, 91))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_19.setGeometry(QtCore.QRect(500, 320, 111, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_20.setGeometry(QtCore.QRect(500, 360, 111, 41))
        self.pushButton_20.setObjectName("pushButton_20")
        self.tabWidget.addTab(self.tab_6, "")

        self.tableWidget_6.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_5.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_4.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_3.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_7.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.tableWidget_2.setSortingEnabled (True)  #默认为False
        self.tableWidget_3.setSortingEnabled (True)  #默认为False
        self.tableWidget_4.setSortingEnabled (True)  #默认为False
        self.tableWidget_5.setSortingEnabled (True)  #默认为False
        self.tableWidget_6.setSortingEnabled (True)  #默认为False
        self.tableWidget_7.setSortingEnabled (True)  #默认为False

        #查询
        self.pushButton.clicked.connect(self.selectorder)
        self.pushButton_8.clicked.connect(self.selectgoods)
        self.pushButton_12.clicked.connect(self.selectcustomer)
        self.pushButton_13.clicked.connect(self.selectbreak)
        self.pushButton_15.clicked.connect(self.selectcomment)
        self.pushButton_17.clicked.connect(self.selectnews)
        #添加
        self.pushButton_3.clicked.connect(self.addorder)
        self.pushButton_5.clicked.connect(self.addgoods)
        self.pushButton_10.clicked.connect(self.addcustomer)
        self.pushButton_14.clicked.connect(self.addbreak)
        self.pushButton_18.clicked.connect(self.addnews)

        #删除
        self.pushButton_2.clicked.connect(self.deleteorder)
        self.pushButton_6.clicked.connect(self.deletegoods)
        self.pushButton_11.clicked.connect(self.deletecustomer)
        self.pushButton_16.clicked.connect(self.deletecomment)
        self.pushButton_19.clicked.connect(self.deletenews)

        #修改
        self.pushButton_7.clicked.connect(self.changeorder)
        self.pushButton_4.clicked.connect(self.changegoods)
        self.pushButton_9.clicked.connect(self.changecustomer)
        self.pushButton_20.clicked.connect(self.changenews)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def changeorder(self):
        self.xgord1.show()
        self.xgord1.pushButton.clicked.connect(self.changeorder1)

    def changeorder1(self):
        phone,roomid,date,book,chein,consume,cheout,time,price = self.xgord1.lineEdit.text(),self.xgord1.lineEdit_2.text(),self.xgord1.lineEdit_3.text(),self.xgord1.lineEdit_4.text(),self.xgord1.lineEdit_5.text(),self.xgord1.lineEdit_6.text(),self.xgord1.lineEdit_7.text(),self.xgord1.lineEdit_8.text(),self.xgord1.lineEdit_9.text()
        row_index = self.tableWidget_2.currentIndex().row()
        lst = []

        for i in range(0, 9):
            lst.append(self.tableWidget_2.item(row_index, i).text())
        if len(phone) == 0 or len(roomid) == 0 or len(date) == 0:
            QMessageBox.information(self.xgord1.pushButton, "提示", "前三项不能为空哦")
            return -1
        cur.execute('delete from orderd where phone = "{}" and roomid = "{}" and date = "{}"'.format(lst[0],lst[1],lst[2]))
        cur.execute('insert into orderd values ("{}","{}","{}","{}","{}","{}","{}","{}","{}")'.format(phone,roomid,date,book,chein,consume,cheout,time,price))
        cur.connection.commit()

        rowPosition = self.tableWidget_2.currentIndex().row()
        self.tableWidget_2.setItem(rowPosition, 0, QTableWidgetItem(phone))
        self.tableWidget_2.setItem(rowPosition, 1, QTableWidgetItem(roomid))
        self.tableWidget_2.setItem(rowPosition, 2, QTableWidgetItem(date))
        self.tableWidget_2.setItem(rowPosition, 3, QTableWidgetItem(book))
        self.tableWidget_2.setItem(rowPosition, 4, QTableWidgetItem(chein))
        self.tableWidget_2.setItem(rowPosition, 5, QTableWidgetItem(consume))
        self.tableWidget_2.setItem(rowPosition, 6, QTableWidgetItem(cheout))
        self.tableWidget_2.setItem(rowPosition, 7, QTableWidgetItem(time))
        self.tableWidget_2.setItem(rowPosition, 8, QTableWidgetItem(price))
        self.xgord1.close()

    def changegoods(self):
        self.xggoo1.show()
        self.xggoo1.pushButton.clicked.connect(self.changegoods1)

    def changegoods1(self):
        id,nm,price,num = self.xggoo1.lineEdit.text(),self.xggoo1.lineEdit_2.text(),self.xggoo1.lineEdit_3.text(),self.xggoo1.lineEdit_4.text()

        row_index = self.tableWidget_3.currentIndex().row()
        lst = []

        for i in range(0, 4):
            lst.append(self.tableWidget_3.item(row_index, i).text())

        if len(id) == 0 :
            QMessageBox.information(self.xggoo1.pushButton, "提示", "物品编号不能为空哦")
            return -1

        cur.execute(
            'delete from goods where id = "{}"'.format(lst[0]))
        cur.execute(
            'insert into goods values ("{}","{}","{}","{}")'.format(nm, id, price, num))
        cur.connection.commit()

        rowPosition = self.tableWidget_3.currentIndex().row()
        self.tableWidget_3.setItem(rowPosition, 0, QTableWidgetItem(id))
        self.tableWidget_3.setItem(rowPosition, 1, QTableWidgetItem(nm))
        self.tableWidget_3.setItem(rowPosition, 2, QTableWidgetItem(price))
        self.tableWidget_3.setItem(rowPosition, 3, QTableWidgetItem(num))
        self.xggoo1.close()

    def changecustomer(self):
        self.xgcus1.show()
        self.xgcus1.pushButton.clicked.connect(self.changecustomer1)

    def changecustomer1(self):
        nm,sex,phone,adress, = self.xgcus1.lineEdit.text(),self.xgcus1.lineEdit_2.text(),self.xgcus1.lineEdit_3.text(),self.xgcus1.lineEdit_4.text()
        id = self.xgcus1.lineEdit_5.text()
        pwd = self.xgcus1.lineEdit_6.text()
        row_index = self.tableWidget_4.currentIndex().row()
        lst = []

        for i in range(0, 6):
            lst.append(self.tableWidget_4.item(row_index, i).text())

        if len(phone) == 0 or len(nm) == 0:
            QMessageBox.information(self.xgcus1.pushButton, "提示", "手机号或姓名不能为空哦")
            return -1
        #123456789012345678
        cur.execute(
            'delete from customer where phone = "{}"'.format(lst[2]))
        cur.execute(
            'insert into customer values ("{}","{}","{}","{}","{}","{}")'.format(nm,sex,phone,adress,id,pwd))
        cur.connection.commit()

        rowPosition = self.tableWidget_4.currentIndex().row()
        self.tableWidget_4.setItem(rowPosition, 0, QTableWidgetItem(nm))
        self.tableWidget_4.setItem(rowPosition, 1, QTableWidgetItem(sex))
        self.tableWidget_4.setItem(rowPosition, 2, QTableWidgetItem(phone))
        self.tableWidget_4.setItem(rowPosition, 3, QTableWidgetItem(adress))
        self.tableWidget_4.setItem(rowPosition, 4, QTableWidgetItem(id))
        self.tableWidget_4.setItem(rowPosition, 5, QTableWidgetItem(pwd))
        self.xgcus1.close()

    def changenews(self):
        self.xgnew1.show()
        self.xgnew1.pushButton.clicked.connect(self.changenews1)

    def changenews1(self):
        id,date,title,content = self.xgnew1.lineEdit.text(),self.xgnew1.lineEdit_2.text(),self.xgnew1.lineEdit_3.text(),self.xgnew1.textEdit.toPlainText()
        row_index = self.tableWidget_7.currentIndex().row()
        lst = []

        for i in range(0, 4):
            lst.append(self.tableWidget_7.item(row_index, i).text())

        if len(id) == 0 or len(title) == 0 or len(date) == 0:
            QMessageBox.information(self.xgnew1.pushButton, "提示", "前三项不能为空哦")
            return -1
        cur.execute(
            'delete from news where adminid = "{}" and date = "{}" and title = "{}"'.format(lst[0],lst[1],lst[2]))
        cur.execute(
            'insert into news values ("{}","{}","{}","{}")'.format(id,date,title,content))
        cur.connection.commit()
        rowPosition = self.tableWidget_7.currentIndex().row()
        self.tableWidget_7.setItem(rowPosition, 0, QTableWidgetItem(id))
        self.tableWidget_7.setItem(rowPosition, 1, QTableWidgetItem(date))
        self.tableWidget_7.setItem(rowPosition, 2, QTableWidgetItem(title))
        self.tableWidget_7.setItem(rowPosition, 3, QTableWidgetItem(content))
        self.xgnew1.close()
    def deleteorder(self):
        row_index = self.tableWidget_2.currentIndex().row()
        lst = []

        for i in range(0, 9):
            lst.append(self.tableWidget_2.item(row_index, i).text())
        print(lst)

        cur.execute('delete from orderd where phone="{}" and roomid="{}" and date = "{}";'.format(lst[0],lst[1],lst[2]))
        cur.execute('update room set state = "空闲" where id = "{}"'.format(lst[1]))
        cur.connection.commit()
        #print('dfgdfgdfgdfgdfgdfg1')
        index = self.tableWidget_2.selectedRanges()  # 1
        index = index[0].bottomRow()
        self.tableWidget_2.removeRow(index)

    def deletegoods(self):
        row_index = self.tableWidget_3.currentIndex().row()
        lst = []

        for i in range(0, 4):
            lst.append(self.tableWidget_3.item(row_index, i).text())
        print(lst)
        cur.execute('delete from goods where id="{}";'.format(lst[0]))
        cur.connection.commit()
        index = self.tableWidget_3.selectedRanges()  # 1
        index = index[0].bottomRow()
        self.tableWidget_3.removeRow(index)

    def deletecustomer(self):
        row_index = self.tableWidget_4.currentIndex().row()
        lst = []

        for i in range(0, 5):
            lst.append(self.tableWidget_4.item(row_index, i).text())
        print(lst)

        cur.execute('delete from customer where phone="{}";'.format(lst[2]))
        cur.connection.commit()
        index = self.tableWidget_4.selectedRanges()  # 1
        index = index[0].bottomRow()
        self.tableWidget_4.removeRow(index)

    def deletecomment(self):
        row_index = self.tableWidget_6.currentIndex().row()
        lst = []

        for i in range(0, 3):
            lst.append(self.tableWidget_6.item(row_index, i).text())
        print(lst)
        cur.execute('delete from comment where phone="{}" and date = "{}" and message = "{}";'.format(lst[0],lst[1],lst[2]))
        cur.connection.commit()
        index = self.tableWidget_6.selectedRanges()  # 1
        index = index[0].bottomRow()
        self.tableWidget_6.removeRow(index)

    def deletenews(self):
        row_index = self.tableWidget_7.currentIndex().row()
        lst = []

        for i in range(0, 4):
            lst.append(self.tableWidget_7.item(row_index, i).text())
        print(lst)
        cur.execute(
            'delete from news where date = "{}" and title = "{}";'.format(lst[1], lst[2]))
        cur.connection.commit()
        index = self.tableWidget_7.selectedRanges()  # 1
        index = index[0].bottomRow()
        self.tableWidget_7.removeRow(index)

    def addorder(self):
        self.xg1.show()
        self.xg1.pushButton.clicked.connect(self.inputorder)

    def inputorder(self):
        phone,roomid,date,book,chein,consume,cheout ,tm,price= self.xg1.lineEdit.text(),self.xg1.lineEdit_2.text(),self.xg1.lineEdit_3.text(),self.xg1.lineEdit_4.text(),self.xg1.lineEdit_5.text(),self.xg1.lineEdit_6.text(),self.xg1.lineEdit_7.text(),self.xg1.lineEdit_8.text(),self.xg1.lineEdit_9.text()
        if len(phone) == 0 or len(roomid) == 0 or len(date) == 0:
            QMessageBox.information(self.xg1.pushButton, "提示", "前三项不能为空哦")
            return -1
        time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        cur.execute('select price from room where id = "{}"'.format(roomid))
        (price) = cur.fetchone()

        cur.execute('insert into orderd values ("{}","{}","{}","{}","{}","{}","{}","{}","{}")'.format(phone,roomid,time,book,chein,consume,cheout,tm,str(price[0])))
        cur.connection.commit()
        rowPosition = self.tableWidget_2.rowCount()
        self.tableWidget_2.insertRow(rowPosition)
        self.tableWidget_2.setItem(rowPosition, 0, QTableWidgetItem(phone))
        self.tableWidget_2.setItem(rowPosition, 1, QTableWidgetItem(roomid))
        self.tableWidget_2.setItem(rowPosition, 2, QTableWidgetItem(date))
        self.tableWidget_2.setItem(rowPosition, 3, QTableWidgetItem(book))
        self.tableWidget_2.setItem(rowPosition, 4, QTableWidgetItem(chein))
        self.tableWidget_2.setItem(rowPosition, 5, QTableWidgetItem(consume))
        self.tableWidget_2.setItem(rowPosition, 6, QTableWidgetItem(cheout))
        self.tableWidget_2.setItem(rowPosition, 7, QTableWidgetItem(tm))
        self.tableWidget_2.setItem(rowPosition, 8, QTableWidgetItem(str(price[0])))
        self.xg1.close()

    def addgoods(self):
        id,nm,price,cnt = self.lineEdit_4.text(),self.lineEdit_5.text(),self.lineEdit_6.text(),self.lineEdit_7.text()

        if len(id) == 0 or len(nm) == 0:
            QMessageBox.information(self.pushButton_5, "提示", "前两项不能为空哦")
            return -1

        cur.execute('insert into goods values ("{}","{}","{}","{}")'.format(nm,id,price,cnt))
        cur.connection.commit()
        rowPosition = self.tableWidget_3.rowCount()
        self.tableWidget_3.insertRow(rowPosition)
        self.tableWidget_3.setItem(rowPosition, 0, QTableWidgetItem(id))
        self.tableWidget_3.setItem(rowPosition, 1, QTableWidgetItem(nm))
        self.tableWidget_3.setItem(rowPosition, 2, QTableWidgetItem(str(price)))
        self.tableWidget_3.setItem(rowPosition, 3, QTableWidgetItem(str(cnt)))

    def addcustomer(self):
        nm,sex,phone,adress,id = self.lineEdit_8.text(),self.lineEdit_9.text(),self.lineEdit_10.text(),self.lineEdit_11.text(),self.lineEdit_12.text()
        if len(nm) == 0 or len(phone) == 0:
            QMessageBox.information(self.pushButton_10, "提示", "名字和手机两项不能为空哦")
            return -1
        #print(type(nm),type(sex),type(phone),type(adress),type(id) )
        cur.execute('insert into customer values ("{}","{}","{}","{}","{}","{}")'.format(nm,sex,phone,adress,id,'1'))
        #cur.execute('insert into customer values ({},{},{},{},{},{})'.format(nm,sex,phone,adress,id,'1'))
        cur.connection.commit()
        rowPosition = self.tableWidget_4.rowCount()
        self.tableWidget_4.insertRow(rowPosition)
        self.tableWidget_4.setItem(rowPosition, 0, QTableWidgetItem(id))
        self.tableWidget_4.setItem(rowPosition, 1, QTableWidgetItem(sex))
        self.tableWidget_4.setItem(rowPosition, 2, QTableWidgetItem(phone))
        self.tableWidget_4.setItem(rowPosition, 3, QTableWidgetItem(adress))
        self.tableWidget_4.setItem(rowPosition, 4, QTableWidgetItem(id))
        self.tableWidget_4.setItem(rowPosition, 5, QTableWidgetItem('1'))

    def addbreak(self):
        phone, roomid, date, id, num = self.lineEdit_16.text(), self.lineEdit_17.text(), self.lineEdit_18.text(), self.lineEdit_19.text(), self.lineEdit_20.text()
        if len(phone) == 0 or len(roomid) == 0 or len(id) == 0:
            QMessageBox.information(self.pushButton_14, "提示", "前四项不能为空哦")
            return -1
        time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        cur.execute('insert into break values ("{}","{}","{}","{}","{}")'.format(phone, roomid, time, id, int(num)))
        cur.connection.commit()

        rowPosition = self.tableWidget_5.rowCount()
        self.tableWidget_5.insertRow(rowPosition)
        self.tableWidget_5.setItem(rowPosition, 0, QTableWidgetItem(phone))
        self.tableWidget_5.setItem(rowPosition, 1, QTableWidgetItem(roomid))
        self.tableWidget_5.setItem(rowPosition, 2, QTableWidgetItem(time))
        self.tableWidget_5.setItem(rowPosition, 3, QTableWidgetItem(id))
        self.tableWidget_5.setItem(rowPosition, 4, QTableWidgetItem(num))

    def addnews(self):
        title, content = self.lineEdit_25.text(), self.textEdit.toPlainText()
        print(title,content,type(content))
        if len(title) == 0 :
            QMessageBox.information(self.pushButton_18, "提示", "标题不能为空哦")
            return -1
        time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        cur.execute('insert into news values ("{}","{}","{}","{}")'.format("root", time, title, content))
        cur.connection.commit()
        rowPosition = self.tableWidget_7.rowCount()
        self.tableWidget_7.insertRow(rowPosition)
        self.tableWidget_7.setItem(rowPosition, 0, QTableWidgetItem('root'))
        self.tableWidget_7.setItem(rowPosition, 1, QTableWidgetItem(time))
        self.tableWidget_7.setItem(rowPosition, 2, QTableWidgetItem(title))
        self.tableWidget_7.setItem(rowPosition, 3, QTableWidgetItem(content))

    def selectbreak(self):
        phone = self.lineEdit_15.text()
        f = 0
        if len(phone) > 0:
            f = 1
        if f == 1:
            cur.execute('select * from break where phone like "%{}%";'.format(phone))
        else:
            return -1
        allitem = cur.fetchall()
        for item in allitem:
            print(item)
            rowPosition = self.tableWidget_5.rowCount()
            self.tableWidget_5.insertRow(rowPosition)
            self.tableWidget_5.setItem(rowPosition, 0, QTableWidgetItem(item[0]))
            self.tableWidget_5.setItem(rowPosition, 1, QTableWidgetItem(item[1]))
            self.tableWidget_5.setItem(rowPosition, 2, QTableWidgetItem(item[2]))
            self.tableWidget_5.setItem(rowPosition, 3, QTableWidgetItem(item[3]))
            self.tableWidget_5.setItem(rowPosition, 4, QTableWidgetItem(str(item[4])))

    def selectcomment(self):
        phone = self.lineEdit_21.text()
        f = 0
        if len(phone) > 0:
            f = 1
        if f == 1:
            cur.execute('select * from comment where phone like "%{}%";'.format(phone))
        else:
            return -1
        allitem = cur.fetchall()
        for item in allitem:
            print(item)
            rowPosition = self.tableWidget_6.rowCount()
            self.tableWidget_6.insertRow(rowPosition)
            self.tableWidget_6.setItem(rowPosition, 0, QTableWidgetItem(item[0]))
            self.tableWidget_6.setItem(rowPosition, 1, QTableWidgetItem(item[1]))
            self.tableWidget_6.setItem(rowPosition, 2, QTableWidgetItem(item[2]))


    def selectnews(self):
        nm = self.lineEdit_22.text()
        f = 0
        if len(nm) > 0:
            f = 1
        if f == 1:
            cur.execute('select * from news where title like "%{}%";'.format(nm))
        else:
            return -1
        allitem = cur.fetchall()
        for item in allitem:
            print(item)
            rowPosition = self.tableWidget_7.rowCount()
            self.tableWidget_7.insertRow(rowPosition)
            self.tableWidget_7.setItem(rowPosition, 0, QTableWidgetItem(item[0]))
            self.tableWidget_7.setItem(rowPosition, 1, QTableWidgetItem(item[1]))
            self.tableWidget_7.setItem(rowPosition, 2, QTableWidgetItem(item[2]))
            self.tableWidget_7.setItem(rowPosition, 3, QTableWidgetItem(item[3]))

    def selectcustomer(self):
        nm = self.lineEdit_13.text()
        phone = self.lineEdit_14.text()
        f, f1 = 0, 0
        if len(nm) > 0:
            f = 1
        if len(phone) > 0:
            f1 = 1

        if f1 == 1:
            if f == 1:
                cur.execute('select * from customer where phone like "%{}%" and name like "%{}%";'.format(phone,nm))
            else:
                cur.execute('select * from customer where phone like "%{}%";'.format(phone))
        elif f == 1:
            cur.execute('select * from customer where customer.name like "%{}%";'.format(nm))

        allitem = cur.fetchall()
        for item in allitem:
            print(item)
            rowPosition = self.tableWidget_4.rowCount()
            self.tableWidget_4.insertRow(rowPosition)
            print(rowPosition)
            self.tableWidget_4.setItem(rowPosition, 0, QTableWidgetItem(item[0]))
            self.tableWidget_4.setItem(rowPosition, 1, QTableWidgetItem(item[1]))
            self.tableWidget_4.setItem(rowPosition, 2, QTableWidgetItem(item[2]))
            self.tableWidget_4.setItem(rowPosition, 3, QTableWidgetItem(item[3]))
            self.tableWidget_4.setItem(rowPosition, 4, QTableWidgetItem(item[4]))
            self.tableWidget_4.setItem(rowPosition, 5, QTableWidgetItem(item[5]))
    def selectgoods(self):
        nm = self.lineEdit_3.text()
        f = 0
        if len(nm) > 0:
            f = 1
        if f == 1:
            cur.execute('select * from goods where name like "%{}%";'.format(nm))
        else:
            return -1
        allitem = cur.fetchall()
        for item in allitem:
            print(item)
            rowPosition = self.tableWidget_3.rowCount()
            self.tableWidget_3.insertRow(rowPosition)
            self.tableWidget_3.setItem(rowPosition, 0, QTableWidgetItem(item[1]))
            self.tableWidget_3.setItem(rowPosition, 1, QTableWidgetItem(item[0]))
            self.tableWidget_3.setItem(rowPosition, 2, QTableWidgetItem(str(item[2])))
            self.tableWidget_3.setItem(rowPosition, 3, QTableWidgetItem(str(item[3])))

    def selectorder(self):
        nm = self.lineEdit.text()
        phone = self.lineEdit_2.text()
        f,f1 = 0,0
        if len(nm) > 0:
            f = 1
        if len(phone) > 0:
            f1 = 1
        #print(f,f1)
        if f1 == 1:
            if f == 1:
                cur.execute('select orderd.* from orderd,customer where orderd.phone = customer.phone and customer.phone like "%{}%" and customer.name like "%{}%";'.format(phone,nm))
            else:
                cur.execute('select * from orderd where phone like "%{}%";'.format(phone))
        elif f == 1:
            cur.execute('select orderd.* from orderd,customer where orderd.phone = customer.phone and customer.name like "%{}%";'.format(nm))
        allitem = cur.fetchall()
        for item in allitem:
            print(item)
            rowPosition = self.tableWidget_2.rowCount()
            self.tableWidget_2.insertRow(rowPosition)
            print(rowPosition)
            self.tableWidget_2.setItem(rowPosition, 0, QTableWidgetItem(item[0]))
            self.tableWidget_2.setItem(rowPosition, 1, QTableWidgetItem(item[1]))
            self.tableWidget_2.setItem(rowPosition, 2, QTableWidgetItem(item[2]))
            self.tableWidget_2.setItem(rowPosition, 3, QTableWidgetItem(item[3]))
            self.tableWidget_2.setItem(rowPosition, 4, QTableWidgetItem(item[4]))
            self.tableWidget_2.setItem(rowPosition, 5, QTableWidgetItem(item[5]))
            self.tableWidget_2.setItem(rowPosition, 6, QTableWidgetItem(item[6]))
            self.tableWidget_2.setItem(rowPosition, 7, QTableWidgetItem(str(item[7])))
            self.tableWidget_2.setItem(rowPosition, 8, QTableWidgetItem(str(item[8])))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "管理员"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "顾客手机号"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "客房号"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "入住日期"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "是否预定"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "是否入住"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "是否结账"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "是否退房"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Form", "时长"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Form", "每天价格"))
        self.pushButton.setText(_translate("Form", "查询订单"))
        self.pushButton_2.setText(_translate("Form", "删除订单"))
        self.pushButton_3.setText(_translate("Form", "添加订单"))
        self.pushButton_7.setText(_translate("Form", "修改订单"))
        self.label.setText(_translate("Form", "姓名"))
        self.label_2.setText(_translate("Form", "手机号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "订单信息"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "物品编号"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "物品名称"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "物品单价"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "物品剩余数量"))
        self.pushButton_4.setText(_translate("Form", "修改物品"))
        self.pushButton_5.setText(_translate("Form", "添加物品"))
        self.pushButton_6.setText(_translate("Form", "删除物品"))
        self.pushButton_8.setText(_translate("Form", "查询物品"))
        self.label_3.setText(_translate("Form", "物品名称"))
        self.label_4.setText(_translate("Form", "物品编号"))
        self.label_5.setText(_translate("Form", "物品名称"))
        self.label_6.setText(_translate("Form", "物品单价"))
        self.label_7.setText(_translate("Form", "数量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "物品信息"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "顾客姓名"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "顾客性别"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "顾客手机号"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Form", "家庭住址"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Form", "身份证号"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("Form", "密码"))
        self.pushButton_9.setText(_translate("Form", "修改顾客信息"))
        self.pushButton_10.setText(_translate("Form", "添加顾客信息"))
        self.label_8.setText(_translate("Form", "顾客姓名"))
        self.label_9.setText(_translate("Form", "顾客性别"))
        self.label_10.setText(_translate("Form", "顾客手机号"))
        self.label_11.setText(_translate("Form", "家庭住址"))
        self.label_12.setText(_translate("Form", "身份证号"))
        self.pushButton_11.setText(_translate("Form", "删除顾客信息"))
        self.pushButton_12.setText(_translate("Form", "查询顾客信息"))
        self.label_13.setText(_translate("Form", "姓名"))
        self.label_14.setText(_translate("Form", "手机号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "顾客信息"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Form", "顾客手机号"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Form", "客房号"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("Form", "日期"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("Form", "物品编号"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("Form", "损坏数量"))
        self.pushButton_13.setText(_translate("Form", "查询损坏物品信息"))
        self.label_15.setText(_translate("Form", "手机号"))
        self.pushButton_14.setText(_translate("Form", "添加损坏物品信息"))
        self.label_16.setText(_translate("Form", "顾客手机号"))
        self.label_17.setText(_translate("Form", "客房号"))
        self.label_18.setText(_translate("Form", "入住日期"))
        self.label_19.setText(_translate("Form", "物品编号"))
        self.label_20.setText(_translate("Form", "损坏数量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "损坏物品信息"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("Form", "顾客手机号"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("Form", "日期"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("Form", "留言"))
        self.pushButton_15.setText(_translate("Form", "查询顾客留言信息"))
        self.label_21.setText(_translate("Form", "手机号"))
        self.pushButton_16.setText(_translate("Form", "删除顾客留言"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "顾客留言"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("Form", "管理员编号"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("Form", "日期"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("Form", "新闻标题"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("Form", "内容"))
        self.pushButton_17.setText(_translate("Form", "查询新闻信息"))
        self.label_22.setText(_translate("Form", "新闻标题"))
        self.pushButton_18.setText(_translate("Form", "添加新闻信息"))
        self.label_23.setText(_translate("Form", "管理员编号"))
        self.label_24.setText(_translate("Form", "日期"))
        self.label_25.setText(_translate("Form", "新闻标题"))
        self.label_26.setText(_translate("Form", "新闻内容"))
        self.pushButton_19.setText(_translate("Form", "删除新闻"))
        self.pushButton_20.setText(_translate("Form", "修改新闻信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "新闻修改"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    Main = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())