# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime
import sys
import mima
from pymysql import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox, QTableWidgetItem

db = connect(
    host='localhost', port=3306, user='root', password='', database='pyconnect'
)

cur = db.cursor()

class xg(QtWidgets.QMainWindow,mima.Ui_Form):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        mima.Ui_Form.__init__(self)
        self.setupUi(self)


class Ui_Form(object):
    def setupUi(self, Form):
        self.xg1 = xg()
        Form.setObjectName("Form")
        Form.resize(507, 394)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 601, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        #self.tableWidget.setSortingEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 401, 371))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(400, 0, 101, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 50, 101, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 100, 101, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(0, 10, 71, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, 70, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 100, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(0, 140, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(0, 170, 71, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(0, 200, 71, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(70, 20, 171, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 80, 171, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 110, 171, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 140, 171, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 170, 171, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(70, 50, 171, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(70, 210, 171, 100))
        self.textEdit.setObjectName("textEdit")

        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 220, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 170, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setTabText(0, "客房信息")
        self.tabWidget.setTabText(1, "个人信息")
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_4.clicked.connect(self.xiugai)
        self.pushButton.clicked.connect(self.display)
        self.pushButton_2.clicked.connect(self.checkin)
        self.pushButton_3.clicked.connect(self.checkout)
        self.pushButton_5.clicked.connect(self.addcomment)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def addcomment(self):
        comment = self.textEdit.toPlainText()
        time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        phone = self.lineEdit_2.text()

        if len(comment) == 0:
            QMessageBox.information(self.pushButton_5, "提示", "留言不能为空！")
            return -1
        cur.execute('insert into comment values ("{}","{}","{}")'.format(phone,time,comment))
        cur.connection.commit()
        QMessageBox.information(self.pushButton_5, "提示", "添加成功！")

    def checkin(self):
        row_index = self.tableWidget.currentIndex().row()
        lst = []

        for i in range(0,4):
            lst.append(self.tableWidget.item(row_index , i).text())
        print(lst)

        time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        if lst[3] != '空闲' :
            QMessageBox.information(self.pushButton_2, "提示", "当前客房已经有人住啦！")
        else :
            cur.execute('insert into orderd(phone,roomid,date,isbook,time,price) values("{}","{}","{}","{}","{}","{}");'
                    .format(self.lineEdit_2.text(), lst[0], time, '1',0,lst[2]))
            self.tableWidget.setItem(row_index, 3, QTableWidgetItem('预定'))
            cur.execute('update room set state = "预定" where id = {}'.format(lst[0]))
            cur.connection.commit()
            QMessageBox.information(self.pushButton_2, "提示", "预订成功")

    def checkout(self):
        row_index = self.tableWidget.currentIndex().row()
        lst = []

        for i in range(0, 4):
            lst.append(self.tableWidget.item(row_index, i).text())
        print(lst)
        if lst[3] == '空闲' :
            QMessageBox.information(self.pushButton_2, "提示", "未预定当前房间")
        else:
            cur.execute('delete from orderd where phone="{}" and roomid="{}";'.format(self.lineEdit_2.text(),lst[0]))
            self.tableWidget.setItem(row_index, 3, QTableWidgetItem('空闲'))
            cur.execute('update room set state = "空闲" where id = {}'.format(lst[0]))
            cur.connection.commit()
            QMessageBox.information(self.pushButton_2, "提示", "退订成功")
    def display(self):
        cur.execute('select * from room;')
        allitem = cur.fetchall()
        cnt = 1;
        for item in allitem:
            print(item)
            rowPosition = self.tableWidget.rowCount()
            self.tableWidget.insertRow(rowPosition)
            self.tableWidget.setItem(rowPosition, 0, QTableWidgetItem(item[0]))
            self.tableWidget.setItem(rowPosition, 1, QTableWidgetItem(item[1]))
            self.tableWidget.setItem(rowPosition, 2, QTableWidgetItem(str(item[2])))
            self.tableWidget.setItem(rowPosition, 3, QTableWidgetItem(item[3]))

    def xiugai(self):
        self.xg1.show()
        self.xg1.pushButton.clicked.connect(self.check)

    def check(self):
        cur.execute('select password from customer where phone={};'.format(self.lineEdit_2.text()))
        (pwd) = cur.fetchone()

        yuan = self.xg1.lineEdit.text()
        xin = self.xg1.lineEdit_2.text()
        print(yuan,pwd[0])
        if yuan != pwd[0]:
            QMessageBox.information(self.pushButton_4, "提示", "旧密码不正确")
        else :
            cur.execute('update customer set password={} where phone="{}";'.format(xin,self.lineEdit_2.text()))
            cur.connection.commit()  # 一定要写这一句！！！！！不然不会保存的！！！
            self.lineEdit_5.setText(xin)
        self.xg1.close()
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "用户"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "客房号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "客房标准"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "客房每小时单价"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "客房状态"))
        self.pushButton.setText(_translate("Form", "显示客房信息"))
        self.pushButton_2.setText(_translate("Form", "预订"))
        self.pushButton_3.setText(_translate("Form", "退订"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "客房信息"))
        self.label.setText(_translate("Form", "姓名"))
        self.label_2.setText(_translate("Form", "性别"))
        self.label_3.setText(_translate("Form", "手机号"))
        self.label_4.setText(_translate("Form", "家庭住址"))
        self.label_5.setText(_translate("Form", "身份证号"))
        self.label_6.setText(_translate("Form", "密码"))
        self.label_7.setText(_translate("Form", "留言"))
        self.pushButton_4.setText(_translate("Form", "修改密码"))
        self.pushButton_5.setText(_translate("Form", "添加留言"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "个人信息"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    Main = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())